import React from 'react';

const TermsAndAgreements: React.FC = () => {
  return (
    <div className="w-full max-w-4xl h-full flex flex-col bg-gray-800/50 backdrop-blur-sm rounded-2xl shadow-2xl border border-gray-700/50 p-6 sm:p-8 text-gray-300 overflow-y-auto">
      <div className="prose prose-sm max-w-none">
        <h2 className="text-3xl font-bold bg-gradient-to-r from-purple-400 to-indigo-500 text-transparent bg-clip-text mb-4">
          Terms & Agreements
        </h2>
        <p>
          Welcome to Melisa AI. By accessing or using our application, you
          agree to be bound by these terms and conditions. If you disagree
          with any part of the terms, you may not access the service.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-2">1. Use of Service</h3>
        <p>
          You agree to use Melisa AI only for lawful purposes and in a way that
          does not infringe the rights of, restrict, or inhibit anyone else's
          use and enjoyment of the application. Prohibited behavior includes
          harassing or causing distress or inconvenience to any other user,
          transmitting obscene or offensive content, or disrupting the normal
          flow of dialogue within the application.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-2">2. Intellectual Property</h3>
        <p>
          The content generated by Melisa AI is for your personal,
          non-commercial use. While you may use the text and images generated,
          BULLETXTECHNOLOGIES retains ownership of the Melisa AI service and
          all underlying technology. You may not duplicate, copy, or reuse any
          portion of the HTML/CSS, Javascript, or visual design elements
          without express written permission.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-2">3. Content Accuracy</h3>
        <p>
          Melisa AI is an experimental service and may produce inaccurate
          information. The information provided is not a substitute for
          professional advice. You should not rely on the information from
          Melisa AI as a sole source of truth or for making critical
          decisions.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-2">4. Limitation of Liability</h3>
        <p>
          In no event shall BULLETXTECHNOLOGIES, nor its directors, employees,
          partners, agents, suppliers, or affiliates, be liable for any
          indirect, incidental, special, consequential or punitive damages,
          including without limitation, loss of profits, data, use, goodwill,
          or other intangible losses, resulting from your access to or use of
          or inability to access or use the service.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-2">5. Changes to Terms</h3>
        <p>
          We reserve the right, at our sole discretion, to modify or replace
          these Terms at any time. We will provide notice of any changes by
          posting the new Terms within the application.
        </p>
      </div>
      <footer className="mt-auto pt-6 text-center text-sm text-gray-400">
        <p>Last updated: {new Date().toLocaleDateString()}</p>
      </footer>
    </div>
  );
};

export default TermsAndAgreements;
